### ISSUE TITLE
建议readme优化一下示例

### ISSUE THREAD

**Issue by snowbitx** [zwight/g6-extension-vue#1]
首先感谢作者解决了我当下的难题。
按照当前readme上的步骤出来是报错的，研究了一会才明白怎么用。
![image](https://github.com/user-attachments/assets/4284d4e0-50db-4caa-8762-ca3ebc98fa18)
可以直接引入自己写的vue组件，显示效果正常。还是挺实用的，再次感谢作者 ❤

**Comment by zwight** [comment]
thanks for your comments，the readme has been updated
